### ISSUE TITLE
Container Orchestrated Device (COD) Workgroup

### ISSUE THREAD

**Issue by RenaudWasTaken** [cncf/sig-runtime#24]
Hello!

Following up to this [email on sig-runtime](https://lists.cncf.io/g/cncf-sig-runtime/message/16), I got a few answers in direct messages. I suspect Github is a better forum to discuss :) !

## General Information

**Goal of the workgroup:** Solve issues related to Device Management across the cloud native space!
**Target Audience:** Both device vendors and container runtime and orchestrator maintainers in this group as well as anyone interested in the area.
**Meetings**: TBD, most likely once every other week at the start

## Immediate Goal
We are creating this working group with the immediate goal in mind to create a common plugin system for all runtimes as well as ensure that the different orchestrator out there end up using this plugin mechanism.

From a vendor and runtime perspective:
- This will lower the entry bar for device support in runtimes
- Allow uniformity and reduce the overall maintenance cost.

From a user perspective:
- Increase the UX Uniformity
- Ensure that the deployment story allows for simple and consistent deployments (e.g: Containers in Kube)

## Broader Charter

Over this immediate milestone, the charter of the group is to solve issues that Devices faces in the cloud native space, such as Intel's over the fabric FPGAs or other use cases that we hope to capture over this groups' lifecycle! 

A draft Charter Document is available here and contributors should feel free to rewrite, reframe or discuss any topic they see fit: https://bit.ly/container-device-interface-wg-charter

## Some Members

- Intel: Ed Bartosh, Ukri Niemimuukko, Alexander Kanevskiy
- Mellanox: Adrian Chiris, Moshe Levi
- NVIDIA: Renaud Gaubert
- Podman: Mnrunal Patel
- Containerd: Mike Brown

We are hoping to start the first meeting by next week and from what I gather from different participants, it looks like we are spread out across the European and North American Time Zones.

See the below doodle for people to indicate what their preferred time is: https://doodle.com/poll/ucchuvc8vxhfftsd

/cc @mikebrow @mrunalp @kad @k82cn @raravena80 @moshe010 @dmcgowan @Random-Liu @yujuhong @adrianchiris @bart0sh @uniemimu

**Comment by zvonkok** [comment]
Hey @RenaudWasTaken count me in, I can help from the Red Hat side regarding all things related to hardware accelerator enablement.

**Comment by RenaudWasTaken** [comment]
Hello everyone!

Based on the results, I've selected Wednesday 06/10 (mm/dd) between 11:00pm and 12:00am PST (or 23:00 to 00:00 PST), the other option was today, but that seemed a bit last minute to me.

We will be using sig-runtime's zoom for the first meeting:  zoom.us/my/cncfsigruntime

I've created an agenda google doc here: https://docs.google.com/document/d/1gUgAMEThkRt4RJ7pA7ZbPPmIOX2Vb7fwH025MjfcTYU/

Here is the draft agenda:

- Administrative stuff:
    - Meeting day, time and recurrence
    - Google Groups
- Charter of the group (getting approval)
    - Are we aligned on short term and long term goals?
    - Do we have a list of concrete deliverables for this group?
    - Discussing with the Network Plumbing Workgroup?
- Kubecon USA
    - Deadline is Sunday, June 28, 2020
    - Submission of a panel?
- [Renaud] CDI
    - Administrative: {Github repo and review process}
    - Deliverables:
        - A specification
        - A golang specification
        - A golang library for merging the OCI spec with the CDI spec
        - A JSON schema for validating JSON specs
    - Architecture questions
        - Where does it fit? At the runc/crun/kata level? At the containerd/podman level?

**Comment by mikebrow** [comment]
Just to make sure so that's Thursday 1am for me :-)

**Comment by RenaudWasTaken** [comment]
Unfortunately yes...
First item on the agenda figuring out a better time!

**Comment by amorenoz** [comment]
Hi @RenaudWasTaken, what is the meeting date/time again? According to the agenda there was a meeting on Wednesday June 10th and another on Monday June 22nd.

**Comment by raravena80** [comment]
@amorenoz afaik Renaud set up the cadence for the regular meeting going forward:

Time: 07:00 AM Pacific Time (US and Canada) Every week on Tue.

**Comment by raravena80** [comment]
Closed the issue as the WG has been already created and setup.

**Comment by raravena80** [comment]
@RenaudWasTaken can we have a doc with the Workgroup Charter in the repo?

**Comment by dims** [comment]
@raravena80 @RenaudWasTaken can we please publish the public information regarding this WG in https://github.com/cncf/sig-runtime README please ?

**Comment by raravena80** [comment]
@dims thanks for bringing it up. We'll put up the public info shortly!
