### ISSUE TITLE
Volcano proposal for sandbox

### ISSUE THREAD

**Issue by raravena80** [cncf/sig-runtime#3]
Tracking the proposal from here:

TOC PR: https://github.com/cncf/toc/pull/318

[Github](https://github.com/volcano-sh/volcano/)
[Slides](https://docs.google.com/presentation/d/1RdplRxmUicu0Y03VoMzap3Fb4amwjvMdLH9K7QxOFiM/edit?usp=sharing)

**Comment by raravena80** [comment]
Tagging @bgrant0607 and @brendanburns (TOC Liaisons)  to check if they have any [feedback](https://github.com/cncf/sig-runtime/blob/master/recommendations/sandbox/volcano.md).

Also,  need help finding TOC sponsors.

**Comment by k82cn** [comment]
Please refer to the following link for the presentation video :  https://youtu.be/krG8X6TYJ74

**Comment by k82cn** [comment]
@bgrant0607 , @brendandburns do you have any feedback on [volcano sandbox proposal](https://github.com/cncf/sig-runtime/blob/master/recommendations/sandbox/volcano.md) ?

**Comment by raravena80** [comment]
We reviewed and recommend sandbox: https://github.com/cncf/sig-runtime/blob/master/recommendations/sandbox/volcano.md. Pending TOC sponsors
