### ISSUE TITLE
Harbor Graduation + DD

### ISSUE THREAD

**Issue by raravena80** [cncf/sig-runtime#7]
TOC PR: https://github.com/cncf/toc/pull/311

[Presentation slides]( https://docs.google.com/presentation/d/12B5dGc8lMxKeKBFS8pGoldBtZaIWBtDYUFSNcG0mnCc/edit?ts=5d9f4ab2#slide=id.g5d0c4feb44_0_0)

**Comment by michmike** [comment]
thank you @raravena80  for performing the due diligence on Harbor on behalf of sig-runtime.

**Comment by raravena80** [comment]
SIG recommendation: https://github.com/cncf/sig-runtime/blob/master/recommendations/graduated/harbor.md
